import userRouter from "./userRouter";
import authenticateRouter from "./authenticateRouter";
import movieRouter from "./movieRouter";
import cinemaRouter from "./cinemaRouter";
import movieHallRouter from "./movieHallRouter";
import roomTypeRouter from "./roomTypeRouter";
import layoutRouter from "./layoutRouter";
import showRouter from "./showRouter";
import seatRouter from "./seatRouter";
import bookingRouter from "./bookingRouter";
import reviewRouter from "./reviewRouter";
import paymentRouter from "./paymentRouter";
import eventRouter from "./eventRouter";
import discountRouter from "./discountRouter";
import foodRouter from "./foodRouter";
import notificationRouter from "./notificationRouter";
import express from "express";
const router = express.Router();

router.use("/authenticate", authenticateRouter);
router.use("/booking", bookingRouter);
router.use("/user", userRouter);
router.use("/movie", movieRouter);
router.use("/cinema", cinemaRouter);
router.use("/movie-hall", movieHallRouter);
router.use("/roomType", roomTypeRouter);
router.use("/layout", layoutRouter);
router.use("/show", showRouter);
router.use("/seat", seatRouter);
router.use("/review", reviewRouter);
router.use("/payment", paymentRouter);
router.use("/event", eventRouter);
router.use("/discount", discountRouter);
router.use("/food", foodRouter);
router.use("/notification", notificationRouter);

export default router;
